/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ercSol from "./Erc.sol";
export type { ercSol };
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export type { ERC20 } from "./Erc.sol/ERC20";
export { ERC20__factory } from "./factories/Erc.sol/ERC20__factory";
export type { XSNAKESToken } from "./Erc.sol/XSNAKESToken";
export { XSNAKESToken__factory } from "./factories/Erc.sol/XSNAKESToken__factory";
export type { XSNShop } from "./Erc.sol/XSNShop";
export { XSNShop__factory } from "./factories/Erc.sol/XSNShop__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
